---

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages" # Used in the UI
    files:
      - label: "Captive Portal Welcome Page"
        name: "welcome"
        file: "site/page/welcome.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Text, name: txt, widget: markdown}
          - {label: Wallpaper, name: wallpaper, widget: image}
