---

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "news"
    label: "News"
    folder: "static/news"
    extension: "json"
    format: "json"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title",     label: "Title",                widget: "string"   }
      - { name: "subtitle",  label: "Subtitle",             widget: "string"   }
      - { name: "date",      label: "Publish Date",         widget: "datetime" }
      - { name: "thumbnail", label: "Featured Image",       widget: "image"    }
      - { name: "negative",  label: "Negative title color", widget: "boolean"  }
      - { name: "body",      label: "Body",                 widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - name: "welcome"
        label: "Captive Portal Welcome Page"
        file: "static/page/welcome.json"
        extension: "json"
        format: "json"
        delete: false
        fields:
          - { name: "title",      label: "Title",                                      widget: "string"   }
          - { name: "wallpaper",  label: "Wallpaper",                                  widget: "image"    }
          - { name: "disclaimer", label: "Disclaimer",                                 widget: "markdown" }
          - { name: "specials",   label: "Today's Specials (if empty will be hidden)", widget: "markdown" }
          - { name: "menu",       label: "PDF Menu",                                   widget: "file"     }
          - { name: "body",       label: "Body",                                       widget: "markdown" }
