---

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages" # Used in the UI
    files:
      - name: "welcome"
        label: "Captive Portal Welcome Page"
        file: "static/page/welcome.json"
        extension: "json"
        format: "json"
        delete: false
        fields:
          - { name: "title",      label: "Title",      widget: "string"   }
          - { name: "wallpaper",  label: "Wallpaper",  widget: "image"    }
          - { name: "disclaimer", label: "Disclaimer", widget: "markdown" }
          - { name: "body",       label: "Body",       widget: "markdown" }
